/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cheatsheet: [
      {
          type: 'autogenerated',
          dirName: 'cheatsheet',
      },
  ],
  writeups: [
      {
          type: 'autogenerated',
          dirName: 'writeups',
      },
  ],
};

module.exports = sidebars;
